#!/bin/sh
DISPLAY=:15
export DISPLAY
# vncserver $DISPLAY
LD_LIBRARY_PATH=/usr/local/lib:/usr/lib64/python2.7/site-packages/pygame:/usr/local/cuda/lib64
export LD_LIBRARY_PATH
#python deep_q_network.py
